export const statusCodesDictionary = {
    "400": "VALIDATION_ERR",
    "404": "NOTFOUND_ERR",
    "409": "CONFILICT_ERR",
    "500": "INTERNAL_SERVER_ERR",
    "200": "SUCCESS_MSG",
    "201": "SUCCESS_CREATE_MSG",
    "401": "UNAUTHORIZED_ERR",
};

export const VALIDATION_ERR = "VALIDATION_ERR";
export const NOTFOUND_ERR = "NOTFOUND_ERR";
export const CONFILICT_ERR = "CONFILICT_ERR";
export const INTERNAL_SERVER_ERR = "INTERNAL_SERVER_ERR";
export const SUCCESS_MSG = "SUCCESS_MSG";
export const SUCCESS_CREATE_MSG = "SUCCESS_CREATE_MSG";
export const UNAUTHORIZED_ERR = "UNAUTHORIZED_ERR";
